services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: onlyfurs
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  rustfs:
    image: rustfs/rustfs:latest
    container_name: rustfs
    restart: unless-stopped
    volumes:
      - rustfs-data:/data
      - rustfs-logs:/logs
    environment:
      - RUSTFS_ACCESS_KEY=secret-key
      - RUSTFS_SECRET_KEY=secret-key
    ports:
      - '9000:9000'
      - '9001:9001'

volumes:
  pgdata:
  rustfs-data:
  rustfs-logs:
